# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RZyJz7kvO7QOOwB41Y9-CYt-9qobbhF-
"""

son = float(input("Iltimos, son kiriting: "))


kvadrat = son ** 2
kub = son ** 3


print(f"Son: {son}")
print(f"Kvadrati: {kvadrat}")
print(f"Kubi: {kub}")